[manifest]
version = "1.0.0"
priority = 0

# G.FUNCS.can_select_card: account for extra_slots_used
# this fucking sucks and only accounts for jokers
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if card.ability.set ~= 'Joker' or #G.jokers.cards < G.jokers.config.card_limit + card_limit then"
position = "at"
match_indent = true
payload = '''
local extra_slots_used = card.ability.extra_slots_used
if card.ability.set ~= 'Joker' or #G.jokers.cards < G.jokers.config.card_limit + card_limit - extra_slots_used then	
'''

# G.FUNCS.use_card: if the button is star_select_consumeable, select it to G.consumeables
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "e.config.button = nil"
position = "before"
match_indent = true
payload = "local button = e.config.button"

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "local select_to = card.area == G.pack_cards and G.pack_cards and booster_obj and SMODS.card_select_area(card, booster_obj) and card:selectable_from_pack(booster_obj)"
position = "after"
match_indent = true
payload = "if button == 'star_select_consumeable' then select_to = 'consumeables' end"

# create_card: if Heist has been redeemed, increase the odds of hidden consumables appearing
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not forced_key and soulable and (not G.GAME.banned_keys['c_soul']) then"
position = "after"
match_indent = true
payload = "    local multiplier = next(SMODS.find_card('v_star_heist')) and 5 or 1"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if pseudorandom('soul_'..v.key.._type..G.GAME.round_resets.ante) > (1 - v.soul_rate) then"
position = "at"
match_indent = true
payload = "if pseudorandom('soul_'..v.key.._type..G.GAME.round_resets.ante) > (1 - (v.soul_rate * multiplier)) then"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > 0.997 then"
position = "at"
match_indent = true
payload = "if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > (1 - (0.003 * multiplier)) then"